#!/usr/bin/env python3
"""
OMEGA Weekly Review Generator
=============================

Auto-generates weekly review agenda from active hypotheses and experiments.

Agenda includes:
- Hypotheses that gained/lost confidence
- Hypotheses to consider killing
- Experiments completed
- Negative results vault additions
- Cross-domain insights
- Recommended next experiments

Usage:
    python weekly_review.py generate
    python weekly_review.py generate --output review.md
"""

import sys
from pathlib import Path
from datetime import datetime, timedelta
from typing import List

_repo_root = Path(__file__).resolve().parent.parent.parent
if str(_repo_root) not in sys.path:
    sys.path.insert(0, str(_repo_root))

from products.breakthrough_engine.hypothesis_ledger import HypothesisLedger, HypothesisStatus


class WeeklyReviewGenerator:
    """Generates weekly review agendas."""

    def __init__(self):
        self.ledger = HypothesisLedger()
        self.review_period_days = 7

    def generate(self) -> str:
        """Generate a weekly review agenda."""
        now = datetime.now()
        week_ago = now - timedelta(days=self.review_period_days)

        all_hypotheses = self.ledger.list()

        strengthened = [h for h in all_hypotheses if h.status == HypothesisStatus.STRENGTHENED]
        weakened = [h for h in all_hypotheses if h.status == HypothesisStatus.WEAKENED]
        active = [h for h in all_hypotheses if h.status == HypothesisStatus.ACTIVE]
        killed = [h for h in all_hypotheses if h.status == HypothesisStatus.KILLED]
        falsified = [h for h in all_hypotheses if h.status == HypothesisStatus.FALSIFIED]

        kill_candidates = [h for h in active if h.confidence < 0.3]

        two_weeks_ago = (now - timedelta(days=14)).isoformat()
        stale = [h for h in active if h.updated_at < two_weeks_ago]

        agenda = f"""
# OMEGA Weekly Review
**Generated:** {now.strftime('%Y-%m-%d %H:%M')}
**Period:** {week_ago.strftime('%Y-%m-%d')} to {now.strftime('%Y-%m-%d')}

---

## 📊 Summary

| Category | Count |
|----------|-------|
| Total Hypotheses | {len(all_hypotheses)} |
| Active | {len(active)} |
| Strengthened | {len(strengthened)} |
| Weakened | {len(weakened)} |
| Killed | {len(killed)} |
| Falsified | {len(falsified)} |

---

## ✅ Hypotheses That Gained Support

"""
        if strengthened:
            for h in strengthened[:5]:
                agenda += f"### {h.id}: {h.claim[:60]}\n"
                agenda += f"- **Confidence:** {h.confidence:.0%}\n"
                agenda += f"- **Evidence:** {len(h.evidence)} items\n\n"
        else:
            agenda += "*None this week*\n\n"

        agenda += """
---

## ⚠️ Hypotheses That Weakened

"""
        if weakened:
            for h in weakened[:5]:
                agenda += f"### {h.id}: {h.claim[:60]}\n"
                agenda += f"- **Confidence:** {h.confidence:.0%}\n"
                agenda += f"- **Consider:** Review evidence or kill\n\n"
        else:
            agenda += "*None this week*\n\n"

        agenda += """
---

## 🔪 Kill Candidates (Confidence < 30%)

**Key rule:** Killing a hypothesis is a win, not a loss.

"""
        if kill_candidates:
            for h in kill_candidates:
                agenda += f"- **{h.id}:** {h.claim[:50]}... ({h.confidence:.0%})\n"
            agenda += "\n**Action:** Vote to kill or provide new evidence.\n"
        else:
            agenda += "*None - all active hypotheses above threshold*\n"

        agenda += """
---

## 😴 Stale Hypotheses (No update in 2 weeks)

"""
        if stale:
            for h in stale:
                agenda += f"- **{h.id}:** {h.claim[:50]}... (last update: {h.updated_at[:10]})\n"
            agenda += "\n**Action:** Update, design experiment, or pause.\n"
        else:
            agenda += "*None - all hypotheses recently updated*\n"

        agenda += """
---

## 🧪 Experiments to Design

Based on active hypotheses, consider experiments that would:

1. **Discriminate** between competing hypotheses
2. **Falsify** low-confidence hypotheses cheaply
3. **Strengthen** promising hypotheses

"""
        for h in active[:3]:
            if h.falsifiers:
                agenda += f"### For {h.id}:\n"
                agenda += f"- Claim: {h.claim[:60]}\n"
                agenda += f"- Falsifiers to test: {', '.join(h.falsifiers[:2])}\n\n"

        agenda += """
---

## 🔴 Red Team Questions

- What are we overconfident about?
- Which assumptions would hurt most if false?
- Where are incentives biasing interpretation?

---

## 📋 Action Items

1. [ ] Review strengthened hypotheses - any ready for translation?
2. [ ] Vote on kill candidates
3. [ ] Assign owners to stale hypotheses
4. [ ] Design next week's experiments

---

*Generated by OMEGA Breakthrough Engine*
"""

        return agenda

    def save(self, output_path: str = None) -> str:
        """Generate and save the review."""
        agenda = self.generate()

        if output_path is None:
            output_path = f"weekly_review_{datetime.now().strftime('%Y%m%d')}.md"

        Path(output_path).write_text(agenda, encoding="utf-8")
        return output_path


# CLI
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="OMEGA Weekly Review Generator")
    parser.add_argument("command", nargs="?", default="generate", help="Command (generate)")
    parser.add_argument("--output", "-o", help="Output file path")

    args = parser.parse_args()

    generator = WeeklyReviewGenerator()

    if args.command == "generate":
        if args.output:
            path = generator.save(args.output)
            print(f"Saved to: {path}")
        else:
            print(generator.generate())
